apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: kube-demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: app
          image: hitman99/demoapp
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "32Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: kube-demo
spec:
  selector:
    app: demo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---

kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: demoapp
  namespace: kube-demo
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - secretName: kube-demo-tls
  rules:
    - host: k8s.adomavicius.com
      http:
        paths:
          - path: /
            backend:
              serviceName: demo-app
              servicePort: 80
