// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "demo": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/hitman99/k8s-101/demo-app/design
// --out=$(GOPATH)/src/github.com/hitman99/k8s-101/demo-app
// --version=v1.3.1

package app
