// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "demo": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/hitman99/k8s-101/demo-app/design
// --out=$(GOPATH)/src/github.com/hitman99/k8s-101/demo-app
// --version=v1.3.1

package app

import (
	"github.com/goadesign/goa"
)

// Health Check (default view)
//
// Identifier: application/json; view=default
type JSON struct {
	// status code
	Code int `form:"code" json:"code" yaml:"code" xml:"code"`
	// system status
	Status string `form:"status" json:"status" yaml:"status" xml:"status"`
}

// Validate validates the JSON media type instance.
func (mt *JSON) Validate() (err error) {
	if mt.Status == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "status"))
	}

	return
}
